# MySQL data
# This must be filled out correctly for the plugin to work.
# RoyalAuth will disable itself if it cannot connect to the database.
mysql:
  address: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "minecraft"
  table_prefix: "ra_"

# What commands can be executed if not logged in?
# You do not need to specify login and register.
# Do not include the /
# Put a "%" in front of the command if it should check for the entire command (for subcommands)
# This checks for aliases; don't add multiple entries for the same command. (/we and /worldedit, for example)
allowed_commands:
  - "%we cui"
  - "help"

# Should players that are not logged in be teleported to their world spawn?
# If this is true, players will be teleported back to their location after
# they log in.
teleport_to_spawn: true

# Should players that aren't logged in be able to chat?
allow_chat_notloggedin: false

# Should the plugin disable if the server is in online mode?
disable_if_onlinemode: true

# How many seconds to wait to kick a player if they don't log in in seconds.
# 300 is five minutes - a touch long
kick_not_logged_in: 300

# Login sessions may be edited here. A session is a length of time from last log out to
# next log in. If a player logs in soon enough from the same IP, they will not need to
# log in again. This allows people to log out and then log back in (read: relog) without
# needing to do /login again.
sessions:
  # Enable sessions?
  enabled: true
  # How long the session should be in seconds. 300 - 5 minutes
  length: 300
  # Check to make sure the IP is the same? You probably want to keep this as true.
  check_ip: true

# Require players to register and login?
# This should usually be true.
# This option is currently untested.
require_register: true

# Valid regex for joining players' names.
# Any name that doesn't match this will be kicked.
# If you don't know regex, don't touch this.
player_regex: "(?i)[\\w\\-]{2,16}"
